#!/usr/bin/env bash
# Check if file or directory exists and determine its type

path="$1"

if [[ -e "$path" ]]; then
    if [[ -f "$path" ]]; then
        echo "File exist and is a regular file"
    elif [[ -d "$path" ]]; then
        if [[ -z "$(ls -A "$path")" ]]; then
            echo "school exists but empty"
        else
            echo "school exists but it's a directory"
        fi
    fi
else
    echo "school doesn't exist"
fi
